//! Every piece of fixed user-facing copy, by identity.
//!
//! Variants are grouped by screen under `// Screen: part` comments. Each catalog lists the
//! same sections in the same order (checked by `tests/catalog_layout.rs`), so a variant's
//! neighbours here are its neighbours in every language. Copy used on several screens lives
//! in "Shared actions and states".

/// A piece of fixed copy. Look it up for a locale with [`text`](crate::text).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Message {
    // App and window: menus, shortcuts and the title bar
    AppName,
    BrandMark,
    CloseWindow,
    Quit,
    ViewMenu,
    ZoomIn,
    ZoomOut,
    ResetZoom,
    Back,
    Forward,
    ToggleSidebar,
    ToggleFullscreen,

    // Navigation: the sidebar pages
    Home,
    MediaList,
    Projects,
    Sessions,
    /// The pages of study material, one per kind.
    Flashcards,
    Diagrams,
    Practice,
    Pipelines,
    Settings,
    Help,

    // Shared actions and states, used on more than one page
    Save,
    Saving,
    SaveError,
    /// Saving a piece of study material did not work.
    SaveMaterialError,
    Cancel,
    Close,
    Retry,
    GoToSettings,
    WorkspaceUnavailable,
    CopyText,
    /// An action on a page did not work.
    ActionError,
    /// The day it is: the Home card of what to do, and the day a conversation divider names.
    Today,
    Yesterday,
    /// Under a minute ago, in the shortest form an age takes.
    Now,
    /// Under a minute ago, as time since.
    JustNow,

    // Search
    Search,
    SearchPlaceholder,
    SearchPrompt,
    SearchNoResults,
    SearchFailed,
    SearchKeywordOnly,
    SearchProjects,
    SearchSessions,
    SearchFiles,
    SearchPassages,
    SearchMessages,
    SearchMove,
    SearchOpen,
    SearchClose,
    /// The keys the palette's footer shows: up, down, enter and escape.
    SearchKeyUp,
    SearchKeyDown,
    SearchKeyEnter,
    SearchKeyEscape,
    /// What a result is, after its name, as accessibility reads a row.
    SearchKindProject,
    SearchKindSession,
    SearchKindFile,
    SearchKindPassage,
    SearchKindMessage,

    // Startup: the first hardware measurement
    StartupTitle,
    StartupIntro,
    StartupMeasuring,
    StartupFailed,
    StartupSkip,

    // Onboarding: the guided tour
    OnboardingSkip,
    OnboardingNext,
    OnboardingStart,
    OnboardingFinish,
    OnboardingWelcomeTitle,
    OnboardingWelcomeIntro,
    OnboardingCaptureTitle,
    OnboardingCaptureText,
    OnboardingAskTitle,
    OnboardingAskText,
    OnboardingReviewTitle,
    OnboardingReviewText,
    OnboardingLookTitle,
    OnboardingLookIntro,
    OnboardingNotesTitle,
    OnboardingNotesIntro,
    OnboardingSampleNote,
    OnboardingSampleFile,
    OnboardingSampleQuestion,
    OnboardingSampleAnswer,
    OnboardingNotesHint,
    OnboardingAiTitle,
    OnboardingAiIntro,
    OnboardingAiDownload,
    OnboardingAiDownloading,
    OnboardingAiDownloaded,
    OnboardingAiChatGpt,
    OnboardingAiChatGptReady,
    OnboardingAiWaitForModels,
    OnboardingAiLater,
    OnboardingAiFailed,
    OnboardingReadyTitle,
    OnboardingReadyIntro,
    OnboardingOpenAiSettings,

    // Home: the dashboard
    GreetingMorning,
    GreetingAfternoon,
    GreetingEvening,
    LoadingDashboard,
    DashboardLoadError,
    TodayDue,
    TodayNothingDue,
    TodayPractise,
    ReviewNow,
    ContinueTitle,
    DashboardNoSessions,
    AllCaughtUp,
    OpenPipelines,
    RecentFiles,
    NoFilesYet,
    OpenLibrary,
    /// Opens a cited file in the Library, from the passage shown over the page.
    OpenInLibrary,
    SeeDetails,
    RunsHere,
    NotRecommendedHere,
    AddFiles,
    NewProjectAction,
    NoProjectsYet,

    // Library: files, import and preview
    LoadingMedia,
    MediaLoadError,
    NoMediaYet,
    AllMedia,
    SearchMedia,
    NoMatchingMedia,
    MediaActions,
    UploadMedia,
    DropMediaFiles,
    /// What a session page or a thread says to an agent or a screen reader: files dropped
    /// on it are attached.
    DropFilesToAttach,
    UploadMediaHint,
    MediaFile,
    ChooseMediaFile,
    AssociateWithProject,
    NoProject,
    ImportingMedia,
    MediaPickerError,
    MediaImportError,
    MediaAssociateError,
    LoadingPreview,
    OpenMedia,
    OpenPage,
    ReadFromFile,
    /// Shows what was read from the top, after a citation opened it at its passage.
    ShowFromStart,
    MediaOpenError,
    DeleteMedia,
    AlertDeleteMedia,
    ConfirmDeleteMedia,
    MediaDeleteError,

    // Library: notes and links written in the app
    NewNote,
    NoteTitle,
    NoteBodyPlaceholder,
    SaveNote,
    NoteIncomplete,
    AddLink,
    LinkPlaceholder,
    AddLinkHint,
    AddingLink,
    LinkMissing,
    MadeSourceError,

    // Projects
    ProjectsSaveError,
    ProjectsDeleteError,
    NewProject,
    CreateProject,
    RenameProject,
    DeleteProject,
    AlertDeleteProject,
    ConfirmDeleteProject,
    ProjectName,
    ProjectNameDescription,
    ProjectNameError,
    ProjectDetailDescription,
    ProjectEmptyDescription,
    ProjectDetails,
    ViewProjectFiles,
    /// A project's exam day.
    ExamDay,
    ExamDayPlaceholder,
    ExamDayHint,
    /// Opens the flashcard reviews, from a project.
    OpenProjectCards,
    /// The heading over a project's pieces of study material.
    ProjectMaterial,
    /// Opens a project's quiz.
    OpenProjectQuiz,

    // Sessions: the list and the conversation
    NewSession,
    LoadingSessions,
    SessionsLoadError,
    SessionsSaveError,
    StartSession,
    StartSessionDescription,
    StartWithRecording,
    StartWithRecordingDescription,
    StartWithFiles,
    StartWithFilesDescription,
    StartWithQuestion,
    StartWithQuestionDescription,
    NoProjectsForSessions,
    ChooseProject,
    GoToProjects,
    SessionEmptyHint,
    DeleteSession,
    AlertDeleteSession,
    ConfirmDeleteSession,
    /// Deleting one note or answer of a session, and what the confirmation says goes with it.
    DeleteMessage,
    AlertDeleteMessage,
    ConfirmDeleteMessage,
    /// Asks for a finished answer again.
    AnswerAgain,
    RegenerateTitle,
    RegeneratingTitle,
    TitleGenerationError,
    LoadingMessages,
    MessagesLoadError,
    ComposerPlaceholder,
    /// Back to the latest notes of a session, from far up its transcript.
    JumpToLatest,
    /// A pasted image could not be saved to attach.
    PasteImageError,
    /// The words a pasted image's file name starts with, before when it was pasted.
    PastedImageName,
    /// Under the mentions offered while one is typed: how to pick one.
    MentionPickerHint,
    /// The menu item that mentions the assistant.
    AskAssistant,
    AttachFiles,
    RemoveAttachment,
    SendMessage,
    SendingMessage,
    SendMessageError,
    /// Above the passages an answer cites.
    AnswerSources,
    ViewDetails,
    NothingRead,
    /// A photo read for text that had none, with what usually helps.
    NoTextInPhoto,
    NoSpeechDetected,
    FileRemovedFromLibrary,
    /// A read that ended without a document, as its kind of file is not read.
    ReadingSwitchedOff,
    /// Above an answer: who wrote it.
    AnswerAuthor,
    /// A finished read of a recording, folded under its file.
    WorkTranscribed,
    /// A finished read of any other file, folded under it.
    WorkRead,

    // Sessions: the thread under an attachment
    ReplyInThread,
    ThreadTitle,
    ThreadComposerPlaceholder,
    ThreadLoadError,

    // Sessions: recording from the microphone
    StartRecording,
    StopRecording,
    RecordingLive,
    /// What a recording is called: the session it starts and the file it saves.
    RecordingSessionTitle,
    RecordingInterrupted,
    ResumeRecording,
    SendRecording,
    DiscardRecording,
    RecordingElsewhere,
    MicrophoneError,
    RecordingFailed,
    RecordingFull,
    RecordingSaveError,

    // Sessions: the job detail panel
    ClosePanel,
    FileDetails,
    OpenOriginal,
    DetailResults,
    DetailNoResults,
    DetailAttempts,
    DetailStarted,
    DetailTook,
    DetailOutput,
    CorrectText,
    CorrectionHint,
    CorrectionStale,
    CorrectionError,
    DetailPreview,

    // Study: material and reviews
    FlashcardsDescription,
    DiagramsDescription,
    LoadingStudy,
    StudyLoadError,
    /// The Flashcards sidebar item that shows what is due and how reviews go.
    ReviewDue,
    MakeMaterial,
    /// A project's row, and its place in the project's page, when a kind of material has not
    /// been made from it yet.
    MaterialNotMade,
    /// Rewrites a piece of material from the project as it is now.
    UpdateMaterial,
    /// A piece's first write that stopped.
    MaterialWriteFailed,
    /// A piece's one status when nothing is outstanding, while its update is being written
    /// with the current text still shown, and when the update failed and the current text
    /// stays.
    MaterialUpToDate,
    MaterialUpdating,
    MaterialUpdateFailed,
    /// Nothing in the project can be made into this kind of material.
    MaterialNothingToMake,
    /// Above the projects with cards due or an exam, on the review page.
    ReviewsByProject,
    /// Under the cards due, on the review page: what reviewing does, or that all is done.
    ReviewDueHint,
    ReviewNothingHint,
    /// An opened set: its cards, turning one, and moving through the deck.
    AllCards,
    CardTapToReveal,
    PreviousCard,
    NextCard,
    KindFlashcards,
    KindDiagram,
    WritingMaterial,
    /// A piece of each kind being written, and what to expect meanwhile.
    WritingFlashcards,
    DrawingDiagram,
    WritingMaterialHint,
    DeleteMaterial,
    AlertDeleteMaterial,
    ConfirmDeleteMaterial,
    AlertDeleteCards,
    ConfirmDeleteCards,
    /// Copying material as text other apps read, and saying it was copied.
    CopyMaterial,
    MaterialCopied,
    /// Saving a diagram as an image, and when that fails.
    SaveImage,
    SaveForAnki,
    /// What a save button says once it has saved.
    MaterialSaved,
    /// The file name material is saved under when its title leaves no name.
    UntitledMaterial,
    StartReview,
    NothingDue,
    /// A project's review progress, beside its figures.
    ProgressComingUp,
    ShowAnswer,
    /// Turns a card shown with its answer back to its question.
    HideAnswer,
    /// Leaves a finished review.
    BackToFlashcards,
    /// Under a card being reviewed: the keys that review it.
    ReviewKeysHint,
    RateAgain,
    RateHard,
    RateGood,
    RateEasy,
    ReviewDone,
    DiagramZoomIn,
    DiagramZoomOut,
    DiagramFit,
    DiagramActualSize,
    DiagramHint,
    FlashcardsHint,
    FlashcardsShowAll,
    FlashcardsHideAll,
    /// Writing one flashcard: its boxes and buttons.
    EditCard,
    CardFront,
    CardBack,
    SaveCard,
    DeleteCard,
    AlertDeleteCard,
    ConfirmDeleteCard,
    AddCard,

    // Practice: endless quizzes over a project
    PracticeDescription,
    LoadingPractice,
    PracticeLoadError,
    /// The Quiz page when there is no project to draw questions from.
    PracticeNoProjects,
    DeletePractice,
    AlertDeletePractice,
    ConfirmDeletePractice,
    QuestionChoice,
    QuestionOpen,
    /// The placeholder of the box an open question is answered in.
    AnswerPlaceholder,
    SubmitAnswer,
    CheckingAnswer,
    WritingQuestion,
    NextQuestion,
    /// Puts a missed question into the practice's flashcards, and says it did.
    AddToFlashcards,
    AddedToFlashcards,
    /// Under a question: the keys that answer it, and those that go on once it is answered.
    ChoiceKeysHint,
    NextKeysHint,
    VerdictCorrect,
    VerdictPartly,
    VerdictIncorrect,
    /// After a graded choice, as accessibility reads it: the right one, and a wrong pick.
    ChoiceCorrect,
    ChoiceIncorrect,
    YourAnswer,
    RightAnswer,
    PracticeResults,
    PracticeNoResults,
    /// A question could not be written: its project has nothing read in it yet.
    PracticeNothingToAsk,

    // Pipelines: the jobs page
    PipelinesDescription,
    LoadingPipelines,
    PipelinesLoadError,
    PipelinesEmpty,
    FilterAll,
    GroupWorking,
    GroupUpNext,
    GroupAttention,
    GroupStopped,
    GroupFinished,
    OpenMaterial,
    OpenPractice,
    OpenSession,
    StartJob,
    StopJob,
    RetryJob,
    JobActionError,
    /// The action that sets up what waiting work needs.
    SetupSignIn,
    SetupAction,

    // Jobs: stages, statuses, activities and problems (chosen from `JobKind` and `ErrorKind`)
    StageFetch,
    StageTranscription,
    StageVision,
    StageReading,
    StageIndex,
    StageEmbed,
    StageTitle,
    StageReply,
    StageRewrite,
    StageArtifact,
    StageQuestion,
    StageGrade,
    StatusQueued,
    StatusWaiting,
    StatusStopped,
    StatusFinished,
    StatusFailed,
    ActivityListening,
    ActivityReading,
    ActivityWorking,
    /// A running job that writes: an answer, study material or a practice question.
    ActivityWriting,
    /// A running job grading an answer.
    ActivityChecking,
    ProblemSignIn,
    ProblemConnection,
    ProblemBusy,
    ProblemNotReadable,
    /// The project holds too little on this to make it from it, and the model said so.
    ProblemNotEnough,
    ProblemModel,
    ProblemSetup,
    /// What a job (not a source's) worked on, such as a session or question, was deleted.
    ProblemGone,
    ProblemUnknown,

    // Settings: general
    SettingsGeneral,
    SettingsAi,
    Language,
    LanguageDescription,
    LanguageMenuSubtitle,
    /// English in its own language, the same in every catalog, so a reader finds theirs.
    EnglishOwnName,
    EnglishOptionSubtitle,
    /// Italian in its own language, the same in every catalog.
    ItalianOwnName,
    ItalianOptionSubtitle,
    Updates,
    UpdatesDescription,
    UpdatesMenuSubtitle,
    UpdateCheck,
    UpdateInstall,
    UpdateChecking,
    UpdateInstalling,
    UpdateCurrent,
    UpdateUnavailable,
    UpdateFailed,
    UpdateReady,
    UpdateBusy,
    Appearance,
    AppearanceDescription,
    AppearanceMenuSubtitle,
    Light,
    LightOptionSubtitle,
    Dark,
    DarkOptionSubtitle,
    TextSize,
    TextSizeHint,
    LanguagePreview,
    PreviewMenus,
    PreviewSizes,
    PreviewTimes,

    // Settings: AI overview
    AiOverview,
    AiOverviewDescription,
    AiOverviewMenuSubtitle,
    AiChecking,
    AiReady,
    AiNeedsSignIn,
    AiNeedsDownload,
    AiLlmPurpose,
    AiTranscriptionPurpose,
    AiSearchPurpose,
    AiSearchPrivate,
    AiSetUp,
    AiOpen,
    AiPrivacyNote,

    // Jobs: the card for work waiting on setup
    SetupLlmTitle,
    SetupLlmBody,
    SetupTranscriptionTitle,
    SetupTranscriptionBody,
    SetupSearchTitle,
    SetupSearchBody,
    SetupResumes,

    // Settings: fields the AI sections share
    LoadingSettings,
    SettingsSaved,
    ModelCopies,
    CountError,
    TestConnection,
    TestingConnection,
    ConnectionOk,
    ConnectionFailed,
    ModelInstalled,
    DownloadModel,
    DownloadingModel,
    ModelDownloadError,

    // Settings: transcription
    Transcription,
    TranscriptionDescription,
    TranscriptionMenuSubtitle,
    TranscriptionLoadError,
    ModelCopiesHint,
    LocalModelReady,
    LocalModelMissing,

    // Settings: language models
    Llm,
    LlmDescription,
    LlmMenuSubtitle,
    LlmLoadError,
    LlmProviderChatGpt,
    LlmTierTiny,
    LlmTierTinySubtitle,
    LlmTierMedium,
    LlmTierMediumSubtitle,
    LlmTierSmart,
    LlmTierSmartSubtitle,
    LlmModelHint,
    ModelGpt6Luna,
    ModelGpt61Sol,
    ModelGpt6Astra,
    LlmTierTestFailed,
    LlmModels,
    LlmChatGptHint,
    LlmChatGptSignIn,
    LlmChatGptWaiting,
    LlmChatGptUsingPlan,
    LlmChatGptNotSharing,
    LlmChatGptAllowPlan,
    LlmChatGptManageUsage,
    LlmChatGptSignOut,
    LlmChatGptSignedIn,
    LlmChatGptSignedOut,
    LlmChatGptSignInNeeded,
    LlmChatGptSignInCancelled,
    LlmChatGptNotEligible,
    /// The browser tab ChatGPT's sign-in returns to, once Study has the account.
    LlmChatGptBrowserDone,
    /// The same tab, when the sign-in did not complete.
    LlmChatGptBrowserFailed,
    LlmChatGptSignInFailed,

    // Settings: this computer
    System,
    SystemDescription,
    SystemMenuSubtitle,
    SysLoadError,
    SysDetected,
    SysMeasured,
    SysDecided,
    SysCores,
    SysMemory,
    SysMemoryAvailable,
    SysSimd,
    SysMatmul,
    SysBandwidth,
    SysMeasuredIn,
    SysSpare,
    SysSearch,
    SysTranscription,
    SysNone,
    SearchModelMissing,
    PlacementNotEnoughMemory,
    PlacementTooSlow,
    SysNotMeasured,
    MeasureAgain,
    SysMeasureError,

    // Settings: processing
    Processing,
    ProcessingDescription,
    ProcessingMenuSubtitle,
    ProcessingLoadError,
    ProcessingReading,
    ProcessingTidying,
    ProcessingSearch,
    ProcessingMaterial,
    ProcessingNotRead,
    /// The card for every piece of material, whatever its files: sifting first.
    ProcessingEveryMaterial,
    /// The list of kinds of file, each opening to its switches.
    ProcessingByKind,
    ProcessingSift,
    ProcessingSiftHint,
    /// How many new flashcards come a day.
    NewCardsPerDay,
    NewCardsPerDayHint,
    SourceAudio,
    SourceVideo,
    SourceImage,
    SourcePdf,
    SourceText,
    SourceCode,
    SourceDocument,
    SourceSpreadsheet,
    SourceSlides,
    SourceArchive,
    SourceWeb,
    SourceLink,
    SourceNote,
    SourceOther,
    ExtractorTranscription,
    ExtractorVision,
    ExtractorOffice,
    ExtractorWeb,
    ExtractorText,
    RefinerTranscript,
    RefinerWhitespace,

    // Help
    HelpDescription,
    /// The Help page's guide: a title and a paragraph for each part of Study.
    HelpCaptureTitle,
    HelpCaptureBody,
    HelpAskTitle,
    HelpAskBody,
    HelpStudyTitle,
    HelpStudyBody,
    HelpPracticeTitle,
    HelpPracticeBody,
    HelpKeysTitle,
    HelpKeysBody,
    ReplayOnboarding,
}
